[package]
name = "pdflens-mcp"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
color-eyre = "0.6.5"
eyre = "0.6.12"
hayro = "0.4.0"
rmcp = { version = "0.8.5", features = ["transport-io"] }
schemars = "1.1.0"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
